title: Jumbled Machine Science
description: >- 
  In the world of "Big Data", it can be hard to find all the information of how to get on the ground running.
  Finally, you found the place that hosts it all from the basic mathematical concepts, to the complexities of
  machine learning.
baseurl: ""  # the subpath of your site, e.g. /blog
url: ""  # the base hostname & protocol for your site
github_username: Alphasupremez  # Your GitHub username (for projects, repositories, etc.)

# Build settings
theme: jekyll-theme-cayman  # You are using the Cayman theme
markdown: kramdown  # Markdown engine used for parsing content
plugins:
  - jekyll-feed  # Add RSS feed generation plugin


# Author Information (Optional)
author:
  name: "jordan Smith"  # Add your name here
  bio: "Data enthusiast with a passion for machine learning."  # A short bio
  github: "Alphasupremez"  # Your GitHub handle (same as above)
  linkedin: "your-linkedin-profile"  # Optional: your LinkedIn profile link


# Social Sharing (Optional, if you want to link your social profiles)
social:
  twitter: "your-twitter-handle"
  facebook: "your-facebook-page"
  linkedin: "your-linkedin-profile"

# Permalink settings (Optional)
permalink: /:year/:month/:day/:title/  # Default permalink structure for blog posts

# Exclude files and folders from being processed by Jekyll
exclude:
  - "README.md"
  - "LICENSE"
  - "node_modules"

# Collections (Optional, if you want to create custom collections like portfolio, etc.)
collections:
  portfolio:
    output: true
    permalink: /portfolio/:title/
